# CG-FUGA CORRUPTA
TP01- CG- CEFET/MG 01/2016

FEITO E TESTADO EM LINUX !!
<img src="https://github.com/pedrohlcastro/CG-fuga-corrupta/blob/master/screenshots/jogo.png?raw=true" />

	PARA RODAR O JOGO EM LINUX BASTA SEGUIR OS SEGUINTE PASSOS:
	
	1- ACESSE VIA TERMINAL A PASTA SRC/ DO JOGO
	2- USE O COMANDO MAKE ALL PARA COMPILAR
	3- USE O COMANDO MAKE CLEAN PARA LIMPAR A PASTA
	4- USE MAKE RUN PARA RODAR

FUNCIONALIDADES:

	1- JUIZ SERGIO MORO É UM INIMIGO TELEGUIADO, CUIDADO!!
	2- CASO ESTEJA CANSADO DE PERDER USE O CHEAT: SETA CIMA, SETA BAIXO 100 VOCE FICARA INVENSIVEL.
	3- P- PAUSE
	4- R- REBOOT
	5- ESC- SAIR
	

